version = 0.1

[default.deploy.parameters]
stack_name = "travel-guided-backend-new"
resolve_s3 = true
s3_prefix = "travel-guided-backend-new"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []

[default.global.parameters]
region = "ap-southeast-1"
